/**
 * Utility functions for displaying user-friendly names
 */

import { UserRole } from '../types';

/**
 * Get friendly display name based on user role and name
 * Converts technical names like "BODSDM^738" to "Director SDM"
 */
export function getFriendlyDisplayName(name: string, role: UserRole): string {
  // Role-based friendly names (Indonesian titles)
  const roleDisplayNames: Record<UserRole, string> = {
    'PMO': 'PMO',
    'Sales/Pre-Sales': 'Sales Manager',
    'Purchasing': 'Purchasing Manager',
    'BOD Finance': 'Direktur Keuangan',
    'BOD Procurement': 'Direktur SDM',
    'BOD Director': 'Direktur Utama',
    'Project Manager': name, // Keep original name for PMs
    'Admin': 'Administrator'
  };

  // If name looks like auto-generated (contains special chars like ^, @, numbers only)
  // or is empty/very short, use role-based display name
  const hasSpecialChars = /[\^@#$%&*]/.test(name);
  const isAutoGenerated = /^[A-Z]{3,}[\^@#]?\d+$/.test(name); // e.g., BODSDM^738
  const isEmailLike = name.includes('@');
  const isTooShort = name.trim().length < 3;

  if (hasSpecialChars || isAutoGenerated || isEmailLike || isTooShort) {
    return roleDisplayNames[role];
  }

  // If name starts with "BOD" or role keywords, use role display name
  const nameLower = name.toLowerCase();
  if (
    nameLower.startsWith('bod') ||
    nameLower.includes('pmo') ||
    nameLower.includes('purchasing') ||
    nameLower.includes('sales') ||
    nameLower.includes('finance') ||
    nameLower.includes('procurement') ||
    nameLower.includes('director')
  ) {
    return roleDisplayNames[role];
  }

  // For proper names (real person names), keep as-is
  return name;
}

/**
 * Get short display name for header/avatar
 * Examples:
 * - "Direktur Keuangan" → "DK"
 * - "John Doe" → "JD"
 * - "PMO" → "PMO"
 */
export function getShortDisplayName(name: string, role: UserRole): string {
  const friendlyName = getFriendlyDisplayName(name, role);

  // Special cases for single-word roles
  if (friendlyName === 'PMO') return 'PMO';

  // Get initials from multi-word names
  const words = friendlyName.split(' ').filter(w => w.length > 0);

  if (words.length === 1) {
    // Single word: take first 2-3 characters
    return words[0].substring(0, Math.min(3, words[0].length)).toUpperCase();
  }

  // Multiple words: take first letter of each word (max 3)
  return words
    .slice(0, 3)
    .map(w => w[0])
    .join('')
    .toUpperCase();
}

/**
 * Get role-based greeting message
 */
export function getRoleGreeting(role: UserRole): string {
  const greetings: Record<UserRole, string> = {
    'PMO': 'Kelola semua material request dari seluruh project',
    'Sales/Pre-Sales': 'Kelola BOQ dan material request untuk project Anda',
    'Purchasing': 'Review dan proses purchase order material',
    'BOD Finance': 'Monitor dan approve budget material request',
    'BOD Procurement': 'Review dan approve procurement decisions',
    'BOD Director': 'Overview seluruh material request dan approval',
    'Project Manager': 'Manage your material requests and track their progress',
    'Admin': 'Full system access for management and configuration'
  };

  return greetings[role];
}
